# ===============================================================
# NexT Custom Config
# ===============================================================

menu:
  home: / || fa fa-home
  categories: /categories/ || fa fa-th
  tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive
  about: /about/ || fa fa-user

scheme: Mist

footer:
  since: 2026
  copyright: 方科工作室

social:
  GitHub: https://github.com/fangkestudio666 || fab fa-github
  E-Mail: mailto:31715000@qq.com || fa fa-envelope

social_icons:
  enable: true
  icons_only: false
  transition: true

links_settings:
  icon: fa fa-globe
  layout: block

links:
  专项债知识: /categories/专项债知识/

back2top:
  enable: true
  sidebar: false
  scrollpercent: true

local_search:
  enable: true

busuanzi_count:
  enable: true
  total_visitors: true
  total_visitors_icon: fa fa-user
  total_views: true
  total_views_icon: fa fa-eye
  post_views: true
  post_views_icon: far fa-eye

darkmode: false
