# Site
title: 方科工作室
subtitle: 工程咨询 | 专项债 | 项目前期策划
description: 专业工程咨询，专注项目前期策划与包装
author: fangkestudio
language: zh-CN

# URL
url: https://fangkestudio666.github.io

# Deployment
deploy:
  type: git
  repo: https://github.com/fangkestudio666/fangkestudio666.github.io.git
  branch: master

# Extensions
theme: next
